-- WHY: v0.4.1 introduces WebP thumbnails generated by the MetadataQueue worker.
-- The thumbnail path is content-addressed (derived from blake3_hash + data_dir),
-- so we only need a cache-side status column to distinguish "ready", "pending",
-- and "failed" from "not yet attempted" (NULL). V003 is additive — nullable
-- columns are safe to ALTER INTO an existing v0.4.0 database; existing rows
-- correctly read as "not yet processed".
--
-- WHY store `thumbnail_path` as well (not just derive on the fly): the worker
-- resolves the on-disk path once at generation time and the desktop layer
-- passes it straight to Tauri's `convertFileSrc`. Persisting the resolved
-- path (vs re-deriving in TS) keeps the FS layout a backend-owned detail.
ALTER TABLE file_metadata ADD COLUMN thumbnail_path TEXT;
ALTER TABLE file_metadata ADD COLUMN thumbnail_status TEXT;

-- WHY partial index: most rows will eventually be `ready`; only the "pending"
-- minority needs fast lookup for a future `perima thumbnail` retry command.
-- Mirrors the `idx_file_metadata_captured` partial-index pattern from V002
-- and keeps the index lean by excluding soft-deleted rows.
CREATE INDEX idx_file_metadata_thumbnail_pending
    ON file_metadata(blake3_hash)
    WHERE thumbnail_status = 'pending' AND deleted_at IS NULL;
