import { render, screen, fireEvent, act } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { okAsync, errAsync } from "neverthrow";
import SearchBar from "../components/SearchBar";
import type { SearchHit } from "../types";

vi.mock("../api", () => ({
  search: vi.fn(),
}));

import * as api from "../api";

const mockSearch = vi.mocked(api.search);

const hit: SearchHit = {
  blake3_hash: "abcdef1234567890",
  volume_id: "vol-1",
  relative_path: "photos/sunset.jpg",
  rank: -1.5,
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.useFakeTimers();
});

afterEach(() => {
  vi.useRealTimers();
});

/**
 * Advance fake timers by `ms` and flush all pending Promises.
 *
 * WHY: `waitFor` polls via real `setTimeout`; with fake timers those polls
 * never fire. `vi.runAllTimersAsync()` advances fake timers AND drains the
 * microtask queue so Promise-based state updates land before assertions.
 */
async function advanceAndFlush(ms: number) {
  await act(async () => {
    vi.advanceTimersByTime(ms);
    // Drain promise microtasks generated by the timer callbacks.
    await Promise.resolve();
    await Promise.resolve();
  });
}

describe("SearchBar", () => {
  it("renders the search input", () => {
    render(<SearchBar onResultClick={vi.fn()} />);
    expect(
      screen.getByRole("searchbox", { name: /search files/i }),
    ).toBeInTheDocument();
  });

  it("shows results after debounce delay", async () => {
    mockSearch.mockReturnValue(okAsync([hit]));
    render(<SearchBar onResultClick={vi.fn()} />);

    fireEvent.change(screen.getByRole("searchbox"), {
      target: { value: "sunset" },
    });

    // Before debounce fires, no dropdown.
    expect(screen.queryByRole("listbox")).not.toBeInTheDocument();

    await advanceAndFlush(300);

    expect(screen.getByRole("listbox")).toBeInTheDocument();
    expect(screen.getByText("photos/sunset.jpg")).toBeInTheDocument();
  });

  it("shows (no results) when search returns empty array", async () => {
    mockSearch.mockReturnValue(okAsync([]));
    render(<SearchBar onResultClick={vi.fn()} />);

    fireEvent.change(screen.getByRole("searchbox"), {
      target: { value: "xyzzy" },
    });

    await advanceAndFlush(300);

    expect(screen.getByText("(no results)")).toBeInTheDocument();
  });

  it("calls onResultClick when a hit is clicked", async () => {
    mockSearch.mockReturnValue(okAsync([hit]));
    const onResultClick = vi.fn();
    render(<SearchBar onResultClick={onResultClick} />);

    fireEvent.change(screen.getByRole("searchbox"), {
      target: { value: "sunset" },
    });

    await advanceAndFlush(300);

    fireEvent.click(screen.getByText("photos/sunset.jpg"));
    expect(onResultClick).toHaveBeenCalledWith(hit);
  });

  it("shows (no results) on search error (non-fatal)", async () => {
    mockSearch.mockReturnValue(errAsync("fts5 error"));
    render(<SearchBar onResultClick={vi.fn()} />);

    fireEvent.change(screen.getByRole("searchbox"), {
      target: { value: "bad query" },
    });

    await advanceAndFlush(300);

    expect(screen.getByText("(no results)")).toBeInTheDocument();
  });

  it("clears results when clear button is clicked", async () => {
    mockSearch.mockReturnValue(okAsync([hit]));
    render(<SearchBar onResultClick={vi.fn()} />);

    fireEvent.change(screen.getByRole("searchbox"), {
      target: { value: "sunset" },
    });

    await advanceAndFlush(300);

    expect(screen.getByRole("listbox")).toBeInTheDocument();

    await act(async () => {
      fireEvent.click(screen.getByLabelText("Clear search"));
    });

    expect(screen.queryByRole("listbox")).not.toBeInTheDocument();
    expect(
      (screen.getByRole("searchbox") as HTMLInputElement).value,
    ).toBe("");
  });
});
