[package]
name = "perima-fs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
perima-core = { path = "../core" }
thiserror.workspace  = true
walkdir.workspace    = true
path-slash.workspace = true
dunce.workspace      = true
tracing.workspace    = true
sysinfo.workspace    = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
