// This file has been generated by Specta. DO NOT EDIT.
// HAND-CRAFTED PLACEHOLDER (Batch D): regenerated by CI on first
// `cargo build --features specta-export` run; bindings-drift CI job
// (Task 12) gates future regeneration. Constructed analytically from
// the post-Batch-D Rust types via specta translation rules in spec §4.2
// + §3 row K. Field names are Rust snake_case (no rename_all applied).
//
// Task 4 additions (fast-hashing): FileUuid, BatchId, BatchHandle, DeviceKind,
// CollisionGroup, VerifiedState, FullHashOutcome, FullHashUnavailableReason,
// CoreError::FullHashUnavailable, AppEvent::VerifyProgress/VerifyComplete,
// InvalidationReason::CollisionsChanged.

// ── Primitive newtypes ────────────────────────────────────────────────

/**
 * BLAKE3-256 content hash as 64-char lowercase hex.
 * Rust: `BlakeHash([u8; 32])` with custom `Serialize` → string.
 */
export type BlakeHash = string;

/**
 * File size in bytes.
 * Rust: `FileSize(pub u64)` — newtype tuple; serde emits as number.
 */
export type FileSize = number;

/**
 * Path relative to a volume root (forward-slash, no leading slash).
 * Rust: `MediaPath(String)` with `#[specta(transparent)]`.
 */
export type MediaPath = string;

/**
 * UUIDv7 volume identifier.
 * Rust: `VolumeId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type VolumeId = string;

/**
 * UUIDv7 device identifier.
 * Rust: `DeviceId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type DeviceId = string;

/**
 * Stable surrogate identifier for a file row in `files`.
 * Rust: `FileUuid(pub uuid::Uuid)` with `#[specta(transparent)]`.
 * Immutable across the file's lifetime; used as FK target instead of
 * `BlakeHash` (since `full_hash` is lazy and `quick_hash` is a fingerprint).
 */
export type FileUuid = string;

/**
 * Stable identifier for a `compute_full_hash_batch` operation.
 * Rust: `BatchId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type BatchId = string;

// ── Enums ────────────────────────────────────────────────────────────

/**
 * Top-level event envelope emitted by the backend on the `app-event` channel.
 * Rust: `AppEvent` with `#[serde(tag = "kind", content = "data")]`.
 *
 * HAND-CRAFTED (Batch E Task 12): env-limited, cannot run
 * `cargo build --features specta-export` locally; CI bindings-drift
 * job gates regeneration.
 */
export type AppEvent =
  | { kind: "File"; data: FileEvent }
  | {
      kind: "ScanCompleted";
      data: {
        volume: VolumeId;
        files_seen: number;
        files_new: number;
        duration_ms: number;
      };
    }
  | { kind: "IndexInvalidated"; data: { reason: InvalidationReason } }
  | {
      kind: "VerifyProgress";
      data: {
        batch_id: BatchId;
        files_done: number;
        files_total: number;
        latest_outcome: FullHashOutcome;
      };
    }
  | { kind: "VerifyComplete"; data: { batch_id: BatchId } }
  // T8 (transcription-v1): 5 channel-only variants emitted by the
  // transcription worker. Hand-crafted (channel events bypass tauri-specta);
  // shapes mirror crates/core/src/events.rs::AppEvent::Transcription*.
  | {
      kind: "TranscriptionStarted";
      data: {
        request_uuid: string;
        file_uuid: string;
        file_name: string;
        queue_size: number;
      };
    }
  | {
      kind: "TranscriptionProgress";
      data: {
        request_uuid: string;
        processed_ms: number;
        total_ms: number | null;
      };
    }
  | {
      kind: "TranscriptionCompleted";
      data: {
        request_uuid: string;
        transcript_id: string;
        file_uuid: string;
        segment_count: number;
        language: string | null;
      };
    }
  | { kind: "TranscriptionCancelled"; data: { request_uuid: string } }
  | {
      kind: "TranscriptionFailed";
      data: {
        request_uuid: string;
        error: TranscriptionError;
      };
    };

/**
 * Categorical reason an index was invalidated. Inner field of
 * AppEvent::IndexInvalidated.data.reason. Wire shape (the whole
 * envelope): `\{kind: "IndexInvalidated", data: \{reason: "TagsChanged"\}\}`.
 *
 * WHY string union (not discriminated union): commit b00d1ad dropped
 * `#[serde(tag = "reason")]`; default Rust enum serde produces bare strings
 * for the inner InvalidationReason value. The outer IndexInvalidated variant
 * is a struct variant with a named `reason` field, so #[serde(content = "data")]
 * wraps the whole struct (\{reason: ...\}) into data — not just the bare string.
 * Wire-shape oracle: crates/core/tests/serialize_shape.rs:303-314 asserts
 * v["data"]["reason"] == "TagsChanged".
 */
export type InvalidationReason =
  | "TagsChanged"
  | "FilesChanged"
  | "MetadataChanged"
  | "SearchIndexRebuilt"
  | "CollisionsChanged";

/**
 * Status of a file location row.
 * Rust: plain unit-variant enum, no serde renaming.
 */
export type LocationStatus = "Active" | "Missing" | "Moved" | "Stale";

/**
 * Filesystem event emitted by the backend watcher.
 * Rust: `#[serde(tag = "type")]` inline-tagged enum.
 *
 * Task 11 (spec §4.8): every variant carries `file_uuid: FileUuid | null`.
 * The watcher emits `null` (no DB lookup at emission time); consumers do
 * their own `(volume, path)` lookup as needed.
 */
export type FileEvent =
  | { type: "Created"; path: MediaPath; volume: VolumeId; file_uuid: FileUuid | null }
  | { type: "Modified"; path: MediaPath; volume: VolumeId; file_uuid: FileUuid | null }
  | { type: "Deleted"; path: MediaPath; volume: VolumeId; file_uuid: FileUuid | null }
  | {
      type: "Renamed";
      from: MediaPath;
      to: MediaPath;
      volume: VolumeId;
      file_uuid: FileUuid | null;
    };

/**
 * Typed error returned by all Tauri command handlers.
 * Rust: `CoreError` with `#[serde(tag = "kind", content = "data")]`.
 */
export type CoreError =
  | { kind: "NotFound"; data: string }
  | { kind: "Duplicate"; data: string }
  | { kind: "InvalidPath"; data: string }
  | { kind: "InvalidHash"; data: string }
  | { kind: "InvalidTag"; data: string }
  | { kind: "Io"; data: { kind: string; message: string } }
  | { kind: "Unsupported"; data: string }
  | { kind: "Internal"; data: string }
  | { kind: "FullHashUnavailable"; data: { reason: FullHashUnavailableReason } }
  | { kind: "BackupFailed"; data: { reason: BackupFailureReason } }
  /**
   * Transcription failure (cloud or local STT backend). Inner payload is the
   * full `TranscriptionError` with its own `kind` discriminant.
   * Rust: `CoreError::Transcription(#[from] TranscriptionError)`.
   */
  | { kind: "Transcription"; data: TranscriptionError };

/**
 * All transcription-adapter failure modes.
 *
 * Rust: `crates/core/src/transcription.rs::TranscriptionError` with
 * `#[serde(tag = "kind", content = "data")]` and `#[non_exhaustive]`.
 *
 * WHY hand-crafted: this enum is a transitive field of
 * `CoreError::Transcription` and `AppEvent::TranscriptionFailed`. Both surfaces
 * cross the IPC boundary; `tauri-specta` walks command-return types but not
 * channel-only types — this enum needs to be in the committed bindings until
 * tauri-specta gains a registered-events emitter.
 */
export type TranscriptionError =
  | { kind: "Network"; data: string }
  | { kind: "Auth" }
  | { kind: "RateLimited"; data: { retry_after_secs: number | null } }
  | { kind: "QuotaExceeded" }
  | { kind: "ModelNotFound"; data: { backend: string; model: string } }
  | { kind: "AudioDecode"; data: string }
  | { kind: "FileTooLarge"; data: { limit_bytes: number } }
  | { kind: "Cancelled" }
  | { kind: "BackendUnavailable"; data: { reason: string } }
  | { kind: "QueueFull"; data: { queued: number } }
  | { kind: "Internal"; data: string };

// ── Structs ──────────────────────────────────────────────────────────

/**
 * A file location row — joined view of `files` + `file_locations`.
 * Rust: `crates/core/src/types.rs::FileLocationRecord`.
 *
 * Task 11 (spec §4.8): `file_uuid` is the stable surrogate for every row;
 * `hash` becomes nullable for files whose `full_hash` has not yet been
 * computed (pending dedup verification).
 */
export type FileLocationRecord = {
  file_uuid: FileUuid;
  hash: BlakeHash | null;
  size: FileSize;
  volume_id: VolumeId;
  relative_path: MediaPath;
  status: LocationStatus;
  first_seen: string;
};

/**
 * A storage volume known to perima.
 * Rust: `crates/core/src/types.rs::VolumeRecord`.
 * Note: `mounts_on_this_machine` wraps `Vec<PathBuf>` → `string[]`.
 */
export type VolumeRecord = {
  id: VolumeId;
  label: string | null;
  capacity_bytes: number;
  is_removable: boolean;
  mounts_on_this_machine: string[];
  last_seen: string;
};

/**
 * Media metadata extracted from a file.
 * Rust: `crates/core/src/metadata.rs::MediaMetadata`.
 */
export type MediaMetadata = {
  hash: BlakeHash;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  captured_at: string | null;
  camera_make: string | null;
  camera_model: string | null;
  codec: string | null;
  bitrate_bps: number | null;
  mime_type: string | null;
  thumbnail_path: string | null;
  thumbnail_status: string | null;
};

/**
 * A user-assignable tag on content.
 * Rust: `crates/core/src/tag.rs::Tag`.
 */
export type Tag = {
  id: string;
  name: string;
  first_seen: string;
};

/**
 * A ranked result from the FTS5 full-text search index.
 * Rust: `crates/core/src/search.rs::SearchHit`.
 *
 * Task 11 (spec §4.8): `file_uuid` is the stable surrogate; `blake3_hash`
 * becomes nullable for pending files (no `full_hash` yet).
 */
export type SearchHit = {
  file_uuid: FileUuid;
  blake3_hash: string | null;
  volume_id: string;
  relative_path: string;
  rank: number;
};

/**
 * Aggregate scan report returned by the `scan` command.
 * Rust: `crates/app/src/scan.rs::ScanReport`.
 * Fields with `#[serde(skip)]` are omitted (`volume_mount`,
 * `per_file_entries`, `manifest_files`).
 */
export type ScanReport = {
  files_seen: number;
  files_new: number;
  files_updated: number;
  files_errored: number;
  bytes_hashed: number;
  duration_ms: number;
  interrupted: boolean;
  volume_label: string | null;
};

/**
 * Outcome of a location verify sweep.
 * Rust: `crates/app/src/verify.rs::VerifyReport`.
 *
 * `skipped_unmounted` counts locations on volumes not mounted on this
 * device. They were NOT checked and their status was NOT changed — a
 * non-zero value means this report describes only part of the library.
 */
export type VerifyReport = {
  checked: number;
  newly_missing: number;
  recovered: number;
  skipped_unmounted: number;
  rows_written: number;
  completed: boolean;
};

/**
 * Outcome of a prune.
 * Rust: `crates/app/src/verify.rs::PruneReport`.
 */
export type PruneReport = {
  missing_found: number;
  rows_pruned: number;
};

/**
 * File location joined with extracted media metadata.
 * Rust: `crates/desktop/src/payloads.rs::FileWithMetadataPayload`.
 * Shell-side flat composite — all fields present, metadata fields
 * nullable when no `file_metadata` row exists.
 *
 * Task 11 (spec §4.8): `file_uuid` is the stable surrogate (always
 * present from V011 on); `hash` is nullable for pending files.
 *
 * Task 14 must-fix: `quick_hash` is exposed so the frontend can detect
 * placeholder rows via `hash === quick_hash`. Pre-V012 `blake3_hash` is
 * NOT NULL, so `hash === null` never fires; equality comparison is the
 * only reliable signal.
 */
export type FileWithMetadataPayload = {
  file_uuid: FileUuid;
  hash: string | null;
  /** Quick-hash value as lowercase hex, or null if backfill not yet run. */
  quick_hash: string | null;
  size: number;
  volume_id: string;
  relative_path: string;
  status: string;
  first_seen: string;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  captured_at: string | null;
  camera_make: string | null;
  camera_model: string | null;
  codec: string | null;
  bitrate_bps: number | null;
  mime_type: string | null;
  thumbnail_path: string | null;
  thumbnail_status: string | null;
  /**
   * Absolute on-disk path joining the volume's current mount root with
   * `relative_path`. `null` when the volume is not currently mounted on
   * this machine — UI controls that need an on-disk path (transcribe,
   * open-file, preview) must be disabled in that case.
   *
   * T9 review fix: pre-fix the frontend passed `relative_path` to the
   * backend `transcribe` command, which forwards untouched to ffmpeg.
   * ffmpeg resolves relative paths against the desktop process cwd,
   * producing silent ENOENT in any normal install.
   */
  absolute_path: string | null;
};

/**
 * File with metadata plus its attached tags.
 * Rust: `crates/desktop/src/payloads.rs::FileWithTagsPayload`
 * with `#[serde(flatten)]` on the `file` field.
 */
export type FileWithTagsPayload = FileWithMetadataPayload & {
  tags: Tag[];
};

// ── Dedup types (Task 4) ─────────────────────────────────────────────

/**
 * Why a `full_hash` could not be produced.
 * Rust: `FullHashUnavailableReason` with `#[serde(tag = "kind")]`.
 */
export type FullHashUnavailableReason =
  | { kind: "NotMounted"; volume_id: string }
  | { kind: "NotComputed" }
  | { kind: "IoError"; message: string };

/**
 * Per-file outcome inside `AppEvent::VerifyProgress`.
 * Rust: `FullHashOutcome` with `#[serde(tag = "outcome", content = "data")]`.
 */
export type FullHashOutcome =
  | { outcome: "Computed"; data: { file_uuid: FileUuid; hash: BlakeHash } }
  | { outcome: "Failed"; data: { file_uuid: FileUuid; error: CoreError } };

/**
 * Returned from `compute_full_hash_batch`.
 * Rust: `BatchHandle` struct.
 */
export type BatchHandle = {
  batch_id: BatchId;
  total: number;
};

/**
 * What kind of physical storage backs a volume.
 * Rust: `DeviceKind` plain enum (no serde tag).
 */
export type DeviceKind = "Hdd" | "Ssd" | "Unknown";

/**
 * State of a candidate duplicate group's verification.
 * Rust: `VerifiedState` plain enum (no serde tag).
 */
export type VerifiedState =
  | "Unverified"
  | "VerifiedDuplicate"
  | "VerifiedDistinct"
  | "Mixed";

/**
 * A group of files sharing the same `quick_hash` — candidate duplicates.
 * Rust: `CollisionGroup` struct in `crates/core/src/dedup.rs`.
 */
export type CollisionGroup = {
  quick_hash: BlakeHash;
  files: FileLocationRecord[];
  verified_state: VerifiedState;
};

// ── Backup types (slice 1, GH #168) ──────────────────────────────────

/**
 * Typed reasons a `BackupDatabaseUseCase::execute` call can fail.
 * Inner payload of `CoreError::BackupFailed`.
 * Rust: `BackupFailureReason` with `#[serde(tag = "kind", content = "data")]`
 * (per `crates/core/src/errors.rs`).
 */
export type BackupFailureReason =
  | { kind: "TargetExists"; data: { path: string } }
  | { kind: "TargetUnwritable"; data: { path: string; message: string } }
  | { kind: "DiskFull"; data: { path: string } }
  | { kind: "AlreadyInProgress" }
  | { kind: "Internal"; data: string };

/**
 * Successful output of `backup_database` / `BackupDatabaseUseCase::execute`.
 * Rust: `BackupOutput` in `crates/app/src/backup.rs`.
 */
export type BackupOutput = {
  /** Absolute path to the freshly written backup file. */
  absolute_path: string;
  /** Size in bytes of the freshly written backup file. */
  size_bytes: number;
};

// ── Transcription types (T7) ─────────────────────────────────────────

/**
 * Returned by the `transcribe` Tauri command — wire-mirror of
 * `perima_app::TranscribeOutput::Started`.
 * Rust: `crates/desktop/src/payloads.rs::TranscribeStartedPayload`.
 */
export type TranscribeStartedPayload = {
  /** Per-request UUIDv7 (lowercase-hex simple form). Pairs with every
   * `AppEvent::Transcription*` variant for this job. */
  request_uuid: string;
  /** 1-based position in the queue at the moment of enqueue. */
  queue_position: number;
};

/**
 * One entry in `ListProvidersPayload.providers`.
 * Rust: `crates/desktop/src/payloads.rs::ProviderListEntry`.
 */
export type ProviderListEntry = {
  /** Provider name (the `[transcription.providers.<name>]` key). */
  name: string;
  /** Preset name (`groq`, `openai`, `custom`, ...). */
  preset: string;
  /** Optional model override; null falls back to the preset's default. */
  model: string | null;
  /** Whether a keyring entry exists for this provider on this device. */
  has_key: boolean;
};

/**
 * Returned by the `list_providers` Tauri command.
 * Rust: `crates/desktop/src/payloads.rs::ListProvidersPayload`.
 */
export type ListProvidersPayload = {
  /** Active provider name from `[transcription].active_provider`, or null. */
  active: string | null;
  /** One entry per provider in `[transcription.providers.*]`. */
  providers: ProviderListEntry[];
};

/**
 * One provider's TOML entry.
 * Rust: `perima_app::config::transcription::ProviderEntry`.
 */
export type ProviderEntry = {
  /** Preset name from `KNOWN_PROVIDERS` (`groq`, `openai`, `custom`). */
  preset: string;
  /** Optional model override; falls back to the preset's default. */
  model: string | null;
  /** Optional `base_url` override (required for `preset = "custom"`). */
  base_url: string | null;
  /** Auth scheme override for custom providers. */
  auth_scheme: string | null;
};

/**
 * Top-level transcription config (one TOML table).
 * Rust: `perima_app::config::transcription::TranscriptionConfig`.
 *
 * Lives at `<config_dir>/config.toml` under the `[transcription]` table.
 * Returned by `get_transcription_config`; accepted by
 * `update_transcription_config`.
 */
export type TranscriptionConfig = {
  /** Active provider name (must match one of `providers.*` keys). */
  active_provider: string | null;
  /** Per-provider configuration table. Empty = no providers wired up yet. */
  providers: { [key: string]: ProviderEntry };
};
