// This file has been generated by Specta. DO NOT EDIT.
// HAND-CRAFTED PLACEHOLDER (Batch D): regenerated by CI on first
// `cargo build --features specta-export` run; bindings-drift CI job
// (Task 12) gates future regeneration. Constructed analytically from
// the post-Batch-D Rust types via specta translation rules in spec §4.2
// + §3 row K. Field names are Rust snake_case (no rename_all applied).
//
// Task 4 additions (fast-hashing): FileUuid, BatchId, BatchHandle, DeviceKind,
// CollisionGroup, VerifiedState, FullHashOutcome, FullHashUnavailableReason,
// CoreError::FullHashUnavailable, AppEvent::VerifyProgress/VerifyComplete,
// InvalidationReason::CollisionsChanged.

// ── Primitive newtypes ────────────────────────────────────────────────

/**
 * BLAKE3-256 content hash as 64-char lowercase hex.
 * Rust: `BlakeHash([u8; 32])` with custom `Serialize` → string.
 */
export type BlakeHash = string;

/**
 * File size in bytes.
 * Rust: `FileSize(pub u64)` — newtype tuple; serde emits as number.
 */
export type FileSize = number;

/**
 * Path relative to a volume root (forward-slash, no leading slash).
 * Rust: `MediaPath(String)` with `#[specta(transparent)]`.
 */
export type MediaPath = string;

/**
 * UUIDv7 volume identifier.
 * Rust: `VolumeId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type VolumeId = string;

/**
 * UUIDv7 device identifier.
 * Rust: `DeviceId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type DeviceId = string;

/**
 * Stable surrogate identifier for a file row in `files`.
 * Rust: `FileUuid(pub uuid::Uuid)` with `#[specta(transparent)]`.
 * Immutable across the file's lifetime; used as FK target instead of
 * `BlakeHash` (since `full_hash` is lazy and `quick_hash` is a fingerprint).
 */
export type FileUuid = string;

/**
 * Stable identifier for a `compute_full_hash_batch` operation.
 * Rust: `BatchId(pub uuid::Uuid)` with `#[specta(transparent)]`.
 */
export type BatchId = string;

// ── Enums ────────────────────────────────────────────────────────────

/**
 * Top-level event envelope emitted by the backend on the `app-event` channel.
 * Rust: `AppEvent` with `#[serde(tag = "kind", content = "data")]`.
 *
 * HAND-CRAFTED (Batch E Task 12): env-limited, cannot run
 * `cargo build --features specta-export` locally; CI bindings-drift
 * job gates regeneration.
 */
export type AppEvent =
  | { kind: "File"; data: FileEvent }
  | {
      kind: "ScanCompleted";
      data: {
        volume: VolumeId;
        files_seen: number;
        files_new: number;
        duration_ms: number;
      };
    }
  | { kind: "IndexInvalidated"; data: { reason: InvalidationReason } }
  | {
      kind: "VerifyProgress";
      data: {
        batch_id: BatchId;
        files_done: number;
        files_total: number;
        latest_outcome: FullHashOutcome;
      };
    }
  | { kind: "VerifyComplete"; data: { batch_id: BatchId } };

/**
 * Categorical reason an index was invalidated. Inner field of
 * AppEvent::IndexInvalidated.data.reason. Wire shape (the whole
 * envelope): `\{kind: "IndexInvalidated", data: \{reason: "TagsChanged"\}\}`.
 *
 * WHY string union (not discriminated union): commit b00d1ad dropped
 * `#[serde(tag = "reason")]`; default Rust enum serde produces bare strings
 * for the inner InvalidationReason value. The outer IndexInvalidated variant
 * is a struct variant with a named `reason` field, so #[serde(content = "data")]
 * wraps the whole struct (\{reason: ...\}) into data — not just the bare string.
 * Wire-shape oracle: crates/core/tests/serialize_shape.rs:303-314 asserts
 * v["data"]["reason"] == "TagsChanged".
 */
export type InvalidationReason =
  | "TagsChanged"
  | "FilesChanged"
  | "MetadataChanged"
  | "SearchIndexRebuilt"
  | "CollisionsChanged";

/**
 * Status of a file location row.
 * Rust: plain unit-variant enum, no serde renaming.
 */
export type LocationStatus = "Active" | "Missing" | "Moved" | "Stale";

/**
 * Filesystem event emitted by the backend watcher.
 * Rust: `#[serde(tag = "type")]` inline-tagged enum.
 */
export type FileEvent =
  | { type: "Created"; path: MediaPath; volume: VolumeId }
  | { type: "Modified"; path: MediaPath; volume: VolumeId }
  | { type: "Deleted"; path: MediaPath; volume: VolumeId }
  | { type: "Renamed"; from: MediaPath; to: MediaPath; volume: VolumeId };

/**
 * Typed error returned by all Tauri command handlers.
 * Rust: `CoreError` with `#[serde(tag = "kind", content = "data")]`.
 */
export type CoreError =
  | { kind: "NotFound"; data: string }
  | { kind: "Duplicate"; data: string }
  | { kind: "InvalidPath"; data: string }
  | { kind: "InvalidHash"; data: string }
  | { kind: "InvalidTag"; data: string }
  | { kind: "Io"; data: { kind: string; message: string } }
  | { kind: "Unsupported"; data: string }
  | { kind: "Internal"; data: string }
  | { kind: "FullHashUnavailable"; data: { reason: FullHashUnavailableReason } };

// ── Structs ──────────────────────────────────────────────────────────

/**
 * A file location row — joined view of `files` + `file_locations`.
 * Rust: `crates/core/src/types.rs::FileLocationRecord`.
 */
export type FileLocationRecord = {
  hash: BlakeHash;
  size: FileSize;
  volume_id: VolumeId;
  relative_path: MediaPath;
  status: LocationStatus;
  first_seen: string;
};

/**
 * A storage volume known to perima.
 * Rust: `crates/core/src/types.rs::VolumeRecord`.
 * Note: `mounts_on_this_machine` wraps `Vec<PathBuf>` → `string[]`.
 */
export type VolumeRecord = {
  id: VolumeId;
  label: string | null;
  capacity_bytes: number;
  is_removable: boolean;
  mounts_on_this_machine: string[];
  last_seen: string;
};

/**
 * Media metadata extracted from a file.
 * Rust: `crates/core/src/metadata.rs::MediaMetadata`.
 */
export type MediaMetadata = {
  hash: BlakeHash;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  captured_at: string | null;
  camera_make: string | null;
  camera_model: string | null;
  codec: string | null;
  bitrate_bps: number | null;
  mime_type: string | null;
  thumbnail_path: string | null;
  thumbnail_status: string | null;
};

/**
 * A user-assignable tag on content.
 * Rust: `crates/core/src/tag.rs::Tag`.
 */
export type Tag = {
  id: string;
  name: string;
  first_seen: string;
};

/**
 * A ranked result from the FTS5 full-text search index.
 * Rust: `crates/core/src/search.rs::SearchHit`.
 */
export type SearchHit = {
  blake3_hash: string;
  volume_id: string;
  relative_path: string;
  rank: number;
};

/**
 * Aggregate scan report returned by the `scan` command.
 * Rust: `crates/app/src/scan.rs::ScanReport`.
 * Fields with `#[serde(skip)]` are omitted (`volume_mount`,
 * `per_file_entries`, `manifest_files`).
 */
export type ScanReport = {
  files_seen: number;
  files_new: number;
  files_updated: number;
  files_errored: number;
  bytes_hashed: number;
  duration_ms: number;
  interrupted: boolean;
  volume_label: string | null;
};

/**
 * File location joined with extracted media metadata.
 * Rust: `crates/desktop/src/payloads.rs::FileWithMetadataPayload`.
 * Shell-side flat composite — all fields present, metadata fields
 * nullable when no `file_metadata` row exists.
 */
export type FileWithMetadataPayload = {
  hash: string;
  size: number;
  volume_id: string;
  relative_path: string;
  status: string;
  first_seen: string;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  captured_at: string | null;
  camera_make: string | null;
  camera_model: string | null;
  codec: string | null;
  bitrate_bps: number | null;
  mime_type: string | null;
  thumbnail_path: string | null;
  thumbnail_status: string | null;
};

/**
 * File with metadata plus its attached tags.
 * Rust: `crates/desktop/src/payloads.rs::FileWithTagsPayload`
 * with `#[serde(flatten)]` on the `file` field.
 */
export type FileWithTagsPayload = FileWithMetadataPayload & {
  tags: Tag[];
};

// ── Dedup types (Task 4) ─────────────────────────────────────────────

/**
 * Why a `full_hash` could not be produced.
 * Rust: `FullHashUnavailableReason` with `#[serde(tag = "kind")]`.
 */
export type FullHashUnavailableReason =
  | { kind: "NotMounted"; volume_id: string }
  | { kind: "NotComputed" }
  | { kind: "IoError"; message: string };

/**
 * Per-file outcome inside `AppEvent::VerifyProgress`.
 * Rust: `FullHashOutcome` with `#[serde(tag = "outcome", content = "data")]`.
 */
export type FullHashOutcome =
  | { outcome: "Computed"; data: { file_uuid: FileUuid; hash: BlakeHash } }
  | { outcome: "Failed"; data: { file_uuid: FileUuid; error: CoreError } };

/**
 * Returned from `compute_full_hash_batch`.
 * Rust: `BatchHandle` struct.
 */
export type BatchHandle = {
  batch_id: BatchId;
  total: number;
};

/**
 * What kind of physical storage backs a volume.
 * Rust: `DeviceKind` plain enum (no serde tag).
 */
export type DeviceKind = "Hdd" | "Ssd" | "Unknown";

/**
 * State of a candidate duplicate group's verification.
 * Rust: `VerifiedState` plain enum (no serde tag).
 */
export type VerifiedState =
  | "Unverified"
  | "VerifiedDuplicate"
  | "VerifiedDistinct"
  | "Mixed";

/**
 * A group of files sharing the same `quick_hash` — candidate duplicates.
 * Rust: `CollisionGroup` struct in `crates/core/src/dedup.rs`.
 */
export type CollisionGroup = {
  quick_hash: BlakeHash;
  files: FileLocationRecord[];
  verified_state: VerifiedState;
};
